# SwiftLint Configuration for Atlas iOS App

# Opt-in rules
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_first_not_nil
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - joined_default_parameter
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - private_action
  - private_outlet
  - prohibited_interface_builder
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - static_operator
  - strong_iboutlet
  - toggle_bool
  - trailing_closure
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# Disabled rules
disabled_rules:
  - trailing_whitespace
  - cyclomatic_complexity
  - function_body_length
  - type_body_length
  - file_length
  - large_tuple
  - nesting

# Included paths
included:
  - Sources
  - Tests

# Excluded paths
excluded:
  - Pods
  - .build
  - DerivedData
  - Package.swift
  - vendor

# Rule configurations
line_length:
  warning: 120
  error: 200
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true

type_name:
  min_length: 3
  max_length:
    warning: 40
    error: 50
  excluded:
    - T
    - U
    - V

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 40
    error: 50
  excluded:
    - id
    - i
    - j
    - k
    - x
    - y
    - z

function_parameter_count:
  warning: 6
  error: 8

large_tuple:
  warning: 3
  error: 4

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 500
  error: 1000
  ignore_comment_only_lines: true

cyclomatic_complexity:
  warning: 15
  error: 25
  ignores_case_statements: true

function_body_length:
  warning: 50
  error: 100

nesting:
  type_level:
    warning: 2
    error: 3
  function_level:
    warning: 3
    error: 5

# Custom rules
custom_rules:
  # Require explicit self for accessing properties and methods
  explicit_self:
    name: "Explicit Self"
    regex: "(\\bself\\.)\\w+"
    message: "Use explicit self for accessing properties and methods"
    severity: warning

  # Avoid force unwrapping
  no_force_unwrap:
    name: "No Force Unwrap"
    regex: "\\!(?!\\=)"
    message: "Avoid using force unwrap (!)"
    severity: error

  # Avoid force cast
  no_force_cast:
    name: "No Force Cast"
    regex: "as!"
    message: "Avoid using force cast (as!)"
    severity: error

  # Prefer guard over if-let for early returns
  prefer_guard:
    name: "Prefer Guard"
    regex: "if\\s+let\\s+\\w+\\s+=\\s+\\w+\\s+\\{\\s+return"
    message: "Prefer guard over if-let for early returns"
    severity: warning

# Reporter type
reporter: "xcode"
